version: '3.8'

services:
  cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: mapme-cosmos-emulator
    ports:
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
    volumes:
      - cosmos-data:/data/db
    networks:
      - mapme-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8081/_explorer/emulator.pem", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  cosmos-data:
    driver: local

networks:
  mapme-network:
    driver: bridge
