version: '3.8'

services:
  cosmos-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    container_name: mapme-cosmos-emulator
    command: ["--protocol", "https"]
    ports:
      - "8081:8081"
      - "1234:1234"
    volumes:
      - cosmos-data:/data/db
    networks:
      - mapme-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8081/_explorer/emulator.pem", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  cosmos-data:
    driver: local

networks:
  mapme-network:
    driver: bridge
