# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Start Cosmos DB Emulator
      run: |
        chmod +x ./scripts/start-cosmos.sh
        ./scripts/start-cosmos.sh
        # Wait for Cosmos DB to be ready
        sleep 30
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        JWT__SecretKey: ${{ secrets.JWT_SECRETKEY }}
        GoogleMaps__ApiKey: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        Google__ClientId: ${{ secrets.GOOGLE_CLIENT_ID }}
        CosmosDb__Endpoint: "https://localhost:8081"
        CosmosDb__Key: "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
        CosmosDb__DatabaseName: "mapme"
        CosmosDb__EnableSSLValidation: "false"
    - name: Stop Cosmos DB Emulator
      if: always()
      run: |
        chmod +x ./scripts/stop-cosmos.sh
        ./scripts/stop-cosmos.sh
